services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./monitoring:/app/monitoring
    environment:
      MLFLOW_TRACKING_URI: sqlite:///mlflow.db
